### ISSUE TITLE
SSL certificate is expired for pool.sks-keyservers.net

### ISSUE THREAD

**Issue by bsmith7581** [SKS-Keyserver/sks-keyserver#81] opened 2020-07-30 07:40 UTC
After reading the following post in the EndeavourOS forum, I did some investigating and found that the issue is an expired certificate. 

https://forum.endeavouros.com/t/are-the-key-servers-down-for-anyone-else/6271

**Comment by ygrek** [comment] 2020-07-30 18:39
I believe the proper place to report is https://lists.nongnu.org/archive/html/sks-devel/
Can you share more details - which url has expired certificated?

**Comment by bsmith7581** [comment] 2020-08-01 08:40
More information: according to this, The certificates for all servers in the pool are expired by now.

https://www.threatshub.org/blog/the-state-of-openpgp-key-servers-kristian-can-you-renew-my-certificate-a-month-later-kristian-ten-days-later-too-late-its-expired/

**Comment by fleish** [comment] 2020-08-03 06:11
`https://www.theregister.com/2020/06/24/openpgp_key_server/`

Rumors of the pool's demise have been greatly (OK, somewhat) exaggerated.

My SSL certificate for the pool was renewed & re-installed on June 25th to return it to the hkps pool. During the time it was expired, it was not published as in DNS as an IP address for hkps.pool.sks-keyservers.net and requests directed to that DNS CNAME should have been serviced by the other servers remaining in the pool with valid SSL certificates. If you are still having issues, you may want to do some debugging to find out the actual reason why.

I'm not sure if it's a typo in the issue title, but you should not be trying to make SSL/HTTPS/HKPS connections to `pool.sks-keyservers.net` as those servers do not have proper certificates for that hostname by design. The only SKS pool that supports SSL/HTTPS/HKPS is `hkps.pool.sks-keyservers.net`. More information can be found here: [https://sks-keyservers.net/overview-of-pools.php](https://sks-keyservers.net/overview-of-pools.php)

**Comment by ygrek** [comment] 2020-08-23 20:22
Closing for lack of details

**Closed by ygrek** 2020-08-23 20:22 UTC
Labels: question
